// Generated by CoffeeScript 1.6.2
(function() {
  app.drawControl = new L.Control.Draw({
    position: "topleft",
    rectangle: {
      shapeOptions: {
        color: "#33cc33",
        weight: 5
      }
    },
    polygon: null,
    polyline: null,
    circle: null,
    marker: null
  });

  app.map.addControl(app.drawControl);

}).call(this);
